print("Введите а")
a = input()
print("a= ", a)
print("Введите в")
b = input()
print("b= ", b)
while data:= input():
	print("Entered:", data)
	print("a=", a)
	print("data=", data)
	print("b=", b)
	print("a>b", a > b)
	print("b>a", b > a)
	print("data>a", data > a)
	print("data<a", data < a)
	print("data>b", data > b)
	print("data<b", data < b)


	print(bool(b < data < a))